### ISSUE TITLE
Ejercicio 1.d) Que es el controlador ssd1306(i2c). Existe alguna shield para controlar una pantalla oled 128x64?; si es así, implemente una practica donde muestre el mensaje “Es fácil el desarrollo con shields”.

### ISSUE THREAD

**Issue by alfredop37** [ISPC-TST-Electronica-Microcontrolada/Grupo4#28]
Que es el controlador ssd1306(i2c). Existe alguna shield para controlar una
pantalla oled 128x64?; si es así, implemente una practica donde muestre el
mensaje “Es fácil el desarrollo con shields”.

**Comment by guelo2019** [comment]
Ok, me pongo a trabajar sobre ello. En primer lugar sobre la documentación del SSD1306 y veré de desarrollar la practica de ejemplo que solicitan.

**Comment by guelo2019** [comment]
Subo al repositorio la documentación sobre el shield OLED (SSD1306)

**Comment by guelo2019** [comment]
Escribí el código de acuerdo a lo requerido y le agregue un plus mas con un mensaje de texto final que se mueve dentro de la pantalla. Haciendo uso de los parámetros que cuenta la librería del fabricante 

- Adafruit_GFX.h

- Adafruit_SSD1306.h
****************************************************************
#define __DEBUG__
#include <Arduino.h>
#include <SPI.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>

// Se define constantes
#define ANCHO_PANTALLA 128 // ancho pantalla OLED
#define ALTO_PANTALLA 64 // alto pantalla OLED

// Objeto de la clase Adafruit_SSD1306
Adafruit_SSD1306 display(ANCHO_PANTALLA, ALTO_PANTALLA, &Wire, -1);

void setup() {
#ifdef __DEBUG__
  Serial.begin(9600);
  delay(100);
  Serial.println("Iniciando pantalla OLED");
#endif

  // Iniciar pantalla OLED en la dirección 0x3C
  if (!display.begin(SSD1306_SWITCHCAPVCC, 0x3C)) {
#ifdef __DEBUG__
    Serial.println("No se encuentra la pantalla OLED");
#endif
    while (true);
  }

  // Limpiar buffer
  display.clearDisplay();

  // Tamaño del texto, 1 corresponde a 8 pixeles en pantalla, 2 a 16 pixeles y asi susecivamente
  display.setTextSize(1);
  // Color del texto
  display.setTextColor(SSD1306_WHITE);
  // Posición del texto
  display.setCursor(3, 32);
  // Escribir texto
  display.println("Es facil el desarrollo con Shields!!");

  // Enviar a pantalla
  display.display();
  delay(2000); //Se muestra el texto principal por 2 segundos en pantalla

}

void loop() {

//Luego de los 2 segundos se muestra otro mensaje 

display.clearDisplay(); // Borra imagen inicial en el OLED
display.setTextSize(1); // Se define el tamaño del texto
display.setTextColor(WHITE); // Se define el color del texto. (mono=>Blanco)
display.setCursor(0,10 ); // Definir posición inicio texto Columna (0) Fila (10)
display.println("Trabajo Practico #1 S4P2 hecho!!"); // Carga la información al buffer
display.display(); // Actualiza display con datos en Buffer
delay(2000); // Demora de 2 segundos.

//Prueba de scroll

// Mover texto de izquierda a derecha
  display.startscrollright(0x00, 0x0F);
  delay(5000);
  display.stopscroll();
  
  // Mover texto de derecha a izquierda
  display.startscrollleft(0x00, 0x0F);
  delay(5000);
  display.stopscroll();
 
  // Mover texto en diagonal hacia la derecha
  display.startscrolldiagright(0x00, 0x07);
  delay(5000);
  display.stopscroll();
 
  // Mover texto en diagonal hacia la izquierda
  display.startscrolldiagleft(0x00, 0x07);
  delay(5000);
  display.stopscroll();

}

****************************************************************
Se probo el código en Proteus


![2022-09-03_131520](https://user-images.githubusercontent.com/46485082/188287831-994f8c95-f824-4204-971b-56c6b41313ee.png)
![2022-09-03_131700](https://user-images.githubusercontent.com/46485082/188287833-e2967640-3834-4c92-855e-22a4b5516c2a.png)
