### ISSUE TITLE
Ejercicio 2.e) Que protocolo utilizan los led ws2812? Hay alguna librería para controlarlos con módulos ESP12 o ESP32? Que se podría armar con los WS2812 y porque el fabricante no utilizo protocolos SPI, UART o I2C?

### ISSUE THREAD

**Issue by alfredop37** [ISPC-TST-Electronica-Microcontrolada/Grupo4#35]
Que protocolo utilizan los led ws2812? Hay alguna librería para controlarlos con
módulos ESP12 o ESP32? Que se podría armar con los WS2812 y porque el
fabricante no utilizo protocolos SPI, UART o I2C?

**Comment by Daninja111** [comment]
Gracias @alfredop37 por estar atento! No hay ninguna complicacion, acabo de subir mis consignas y de paso eliminar mi rama. Todo clean, saludos
