### ISSUE TITLE
Ejercicio 2.f) Enumere otros protocolos de comunicación que no sean de campo y descríbalos brevemente.

### ISSUE THREAD

**Issue by alfredop37** [ISPC-TST-Electronica-Microcontrolada/Grupo4#36]
Enumere otros protocolos de comunicación que no sean de campo y descríbalos
brevemente.

**Comment by guelo2019** [comment]
Ok, me pongo a trabajar sobre ello.

**Comment by alfredop37** [comment]
@guelo2019 como venís con este tema?

**Comment by guelo2019** [comment]
Hola @alfredop37 , estoy trabajando en el informe y estimo subirlo al repo mañana. Así antes del 05/09 esta todo lo solicitado.

**Comment by alfredop37** [comment]
Perfecto! @guelo2019  avisa si necesitas ayuda.

Saludos.

**Comment by guelo2019** [comment]
Ya subí al repositorio la documentación solicitada.
