### ISSUE TITLE
A guardar a guardar cada cosa en su lugar...

### ISSUE THREAD

**Issue by Daninja111** [ISPC-TST-Electronica-Microcontrolada/Grupo4#42]
Chiquis no olvidemos **eliminar** las ramas secundarias luego de ocuparlas asi nos queda solo el main, les dejo el comando para realizarlo desde el git bash, ubiquense desde el main y luego sabiendo el nombre de la rama:

git push origin :nombre de la rama
![image](https://user-images.githubusercontent.com/89562060/188334295-51f93b92-a788-43ff-8a6d-080783300f0c.png)

quedan las de maximo, peridoo 2 y guelo por borrar.

Saludos!

**Comment by alfredop37** [comment]
Ok @Daninja111, Gracias por la info.

Saludos.
