### ISSUE TITLE
CREAR PRESENTACION

### ISSUE THREAD

**Issue by ivanexegomez** [ISPC-TST-Electronica-Microcontrolada/Grupo4#45]

**Comment by guelo2019** [comment]
Procedo a realizar la base de la presentación de nuestro proyecto

**Comment by Daninja111** [comment]
Podemos ir agregando la info a la presentación base @guelo2019 ?

**Comment by guelo2019** [comment]
subo al repositorio el ppt, denle una revisión y agreguen o quiten lo que consideren.

**Comment by alfredop37** [comment]
@guelo2019 perfecto! lo analizamos en la reunion de grupo.
