### ISSUE TITLE
Recopilacion de información 

### ISSUE THREAD

**Issue by guelo2019** [ISPC-TST-Electronica-Microcontrolada/Grupo4#63]
Recopilar información sobre la temática del proyecto y adjuntar a la carpeta establecida.

**Comment by guelo2019** [comment]
Se asigna tarea al equipo. La documentación ir subiendo al repositorio.
Buscar dispositivos que componen un sistema de semaforizacion: Sensores, sistemas de tableros inteligentes, baterías de Litio etc., etc., etc.

**Comment by Daninja111** [comment]
Muy bien, vamos con eso! 💪

**Comment by guelo2019** [comment]
Se completo tarea de recopilación.
